blank_issues_enabled: false
contact_links:
  - name: Development Guide
    url: https://github.com/UWL-CODERS/website/blob/main/DEVELOPMENT.md
    about: Learn how to contribute or develop for the CODERS Club website
  - name: General Support
    url: https://github.com/UWL-CODERS/website?tab=readme-ov-file#getting-help
    about: Ask questions or request help for the CODERS Club website